version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    # HACK: It is necessary for enabling to access from this container to processes out of this container.
    extra_hosts:
      - host_os:${HOST_IP_ADDRESS}
    env_file: .env
    ports:
      - 8050:8050
    # links:
    #   - mysql
    working_dir: /opt
    volumes:
      - ./:/opt
    command: python app.py
    # INFO: Following two lines are necessary for `docker attach container_name`
    stdin_open: true
    tty: true

  # mysql:
  #   image: mysql:5.7
  #   env_file: .env
  #   command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./:/home/root/project
  #     - db:/var/lib/mysql

volumes:
  db:
